import { randomBytes } from "node:crypto";

const ALPHABET = "0123456789abcdefghijklmnopqrstuvwxyz";

/** sec_ = questionnaire section, q_ = question, ind_ = scoring indicator. */
export type KeyPrefix = "sec" | "q" | "ind";

/**
 * Generates a stable key such as "q_k3f9a0b2c7d1". Keys are generated by the system, never typed
 * by people, and never reused: pass every key the cycle has ever used in `taken` (spec §5.4).
 */
export function newKey(prefix: KeyPrefix, taken: ReadonlySet<string> = new Set()): string {
  for (let attempt = 0; attempt < 10; attempt += 1) {
    let suffix = "";
    for (const byte of randomBytes(10)) {
      suffix += ALPHABET.charAt(byte % ALPHABET.length);
    }
    const key = `${prefix}_${suffix}`;
    if (!taken.has(key)) {
      return key;
    }
  }
  throw new Error("Could not generate an unused key");
}
